development:
  adapter: mysql
  database: myvolume_dev
  username: root
  password:
  host: localhost
  
test:
  adapter: mysql
  database: myvolume_dev
  username: root
  password:
  host: localhost
  
production:
  adapter: mysql
  database: myvolume_dev
  username: root
  password:
  host: localhost
